language: python
python:
  - "2.6"
  - "2.7"
before_install:
    - curl -L -o /tmp/0.6.4_linux_amd64.zip https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
    - unzip /tmp/0.6.4_linux_amd64.zip
    - ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
    - pip install python-coveralls
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script: 
  - python ConsulAlertingKVBootstrap.py
  - nosetests --with-coverage --cover-package consulalerting
after_success:  
  - coveralls
